export const mockData = [
  {
    name: 'Дибенко',
    fullName: 'ФОП Дибенко',
    category: 'buyer',
    categoryPrice: 'bulk',
    taxNumber: null,
    contractNumber: null,
    date: null,
    email: null,
    phone: null,
    adress: null,
    active: true,
    relatedCompanies: [],
    listOrderedItems: [
      { value: 1, label: 'Большие цифры', count: 8 },
      { value: 2, label: 'Большие буквы', count: 12 },
      { value: 3, label: 'Веселый дачник', count: 15 },
      { value: 4, label: 'Гигант сканворд', count: 20 },
      { value: 5, label: 'Дарья', count: 25 },
      { value: 6, label: 'Дарья Сканворд', count: 18 },
      { value: 7, label: 'Дача и дачники', count: 10 },
      { value: 8, label: 'Дачные советы', count: 14 },
      { value: 9, label: 'Дачный сканворд', count: 22 },
      { value: 10, label: 'Ежик', count: 30 },
      { value: 11, label: 'Загадки истории', count: 16 },
      { value: 12, label: 'Ключворд', count: 19 },
      { value: 13, label: 'Крупный шрифт', count: 11 },
      { value: 14, label: 'Мир судоку', count: 24 },
      { value: 15, label: 'Страна сканвордов', count: 17 },
      { value: 16, label: 'Тайны и загадки', count: 13 },
      { value: 17, label: 'Тайны ХХ века', count: 21 },
      { value: 18, label: 'Тещин компот', count: 9 },
      { value: 19, label: 'Тещин компот.Судоку', count: 26 },
      { value: 20, label: 'Титан-кроссворд', count: 15 },
      { value: 21, label: 'Филворд Дарья', count: 12 },
      { value: 22, label: '1000 Секретов', count: 10 },
      { value: 23, label: 'ЗОЖ', count: 5 },
      { value: 24, label: 'Бабушкин пирог', count: 15 },
      { value: 25, label: 'Кулинарный альбом', count: 20 },
    ],
    dateOfLastOrderChange: '2025/10/10',
    id: '10',
  },
  {
    name: 'Автовокзал',
    fullName: 'ТТ Автовокзал',
    category: 'buyer',
    categoryPrice: 'retail',
    taxNumber: null,
    contractNumber: null,
    date: null,
    email: null,
    phone: null,
    adress: null,
    active: true,
    relatedCompanies: [],
    listOrderedItems: [
      { value: 1, label: 'Большие цифры', count: 5 },
      { value: 2, label: 'Большие буквы', count: 10 },
      { value: 3, label: 'Веселый дачник', count: 6 },
      { value: 4, label: 'Гигант сканворд', count: 2 },
      { value: 5, label: 'Дарья', count: 7 },
      { value: 6, label: 'Дарья Сканворд', count: 8 },
      { value: 7, label: 'Дача и дачники', count: 1 },
      { value: 8, label: 'Дачные советы', count: 4 },
      { value: 9, label: 'Дачный сканворд', count: 2 },
      { value: 10, label: 'Ежик', count: 30 },
      { value: 11, label: 'Загадки истории', count: 6 },
      { value: 12, label: 'Ключворд', count: 9 },
      { value: 13, label: 'Крупный шрифт', count: 11 },
      { value: 14, label: 'Мир судоку', count: 4 },
      { value: 15, label: 'Страна сканвордов', count: 1 },
      { value: 16, label: 'Тайны и загадки', count: 3 },
      { value: 17, label: 'Тайны ХХ века', count: 21 },
      { value: 18, label: 'Тещин компот', count: 9 },
      { value: 19, label: 'Тещин компот.Судоку', count: 6 },
      { value: 20, label: 'Титан-кроссворд', count: 5 },
      { value: 21, label: 'Филворд Дарья', count: 2 },
      { value: 22, label: '1000 Секретов', count: 10 },
      { value: 23, label: 'ЗОЖ', count: 5 },
      { value: 24, label: 'Бабушкин пирог', count: 5 },
    ],
    dateOfLastOrderChange: '2025/11/05',
    id: '11',
  },
];