// export const mockData = [
//   {
//     name: 'Дибенко',
//     fullName: 'ФОП Дибенко',
//     category: 'buyer',
//     categoryPrice: 'bulk',
//     taxNumber: null,
//     contractNumber: null,
//     date: null,
//     email: null,
//     phone: null,
//     adress: null,
//     active: true,
//     relatedCompanies: [],
//     listOrderedItems: [
//       { value: 1, label: 'Большие цифры', count: 8 },
//       { value: 2, label: 'Большие буквы', count: 12 },
//       { value: 3, label: 'Веселый дачник', count: 15 },
//       { value: 4, label: 'Гигант сканворд', count: 20 },
//       { value: 5, label: 'Дарья', count: 25 },
//       { value: 6, label: 'Дарья Сканворд', count: 18 },
//       { value: 7, label: 'Дача и дачники', count: 10 },
//       { value: 8, label: 'Дачные советы', count: 14 },
//       { value: 9, label: 'Дачный сканворд', count: 22 },
//       { value: 10, label: 'Ежик', count: 30 },
//       { value: 11, label: 'Загадки истории', count: 16 },
//       { value: 12, label: 'Ключворд', count: 19 },
//       { value: 13, label: 'Крупный шрифт', count: 11 },
//       { value: 14, label: 'Мир судоку', count: 24 },
//       { value: 15, label: 'Страна сканвордов', count: 17 },
//       { value: 16, label: 'Тайны и загадки', count: 13 },
//       { value: 17, label: 'Тайны ХХ века', count: 21 },
//       { value: 18, label: 'Тещин компот', count: 9 },
//       { value: 19, label: 'Тещин компот.Судоку', count: 26 },
//       { value: 20, label: 'Титан-кроссворд', count: 15 },
//       { value: 21, label: 'Филворд Дарья', count: 12 },
//       { value: 22, label: '1000 Секретов', count: 10 },
//       { value: 23, label: 'ЗОЖ', count: 5 },
//       { value: 24, label: 'Бабушкин пирог', count: 15 },
//       { value: 25, label: 'Кулинарный альбом', count: 20 },
//     ],
//     dateOfLastOrderChange: '2025/10/10',
//     stockType: 'shop',
//     stockNumber: 2,
//     id: '10',
//   },
//   {
//     name: 'Автовокзал',
//     fullName: 'ТТ Автовокзал',
//     category: 'buyer',
//     categoryPrice: 'retail',
//     taxNumber: null,
//     contractNumber: null,
//     date: null,
//     email: null,
//     phone: null,
//     adress: null,
//     active: true,
//     relatedCompanies: [],
//     listOrderedItems: [
//       { value: 1, label: 'Большие цифры', count: 5 },
//       { value: 2, label: 'Большие буквы', count: 10 },
//       { value: 3, label: 'Веселый дачник', count: 6 },
//       { value: 4, label: 'Гигант сканворд', count: 2 },
//       { value: 5, label: 'Дарья', count: 7 },
//       { value: 6, label: 'Дарья Сканворд', count: 8 },
//       { value: 7, label: 'Дача и дачники', count: 1 },
//       { value: 8, label: 'Дачные советы', count: 4 },
//       { value: 9, label: 'Дачный сканворд', count: 2 },
//       { value: 10, label: 'Ежик', count: 30 },
//       { value: 11, label: 'Загадки истории', count: 6 },
//       { value: 12, label: 'Ключворд', count: 9 },
//       { value: 13, label: 'Крупный шрифт', count: 11 },
//       { value: 14, label: 'Мир судоку', count: 4 },
//       { value: 15, label: 'Страна сканвордов', count: 1 },
//       { value: 16, label: 'Тайны и загадки', count: 3 },
//       { value: 17, label: 'Тайны ХХ века', count: 21 },
//       { value: 18, label: 'Тещин компот', count: 9 },
//       { value: 19, label: 'Тещин компот.Судоку', count: 6 },
//       { value: 20, label: 'Титан-кроссворд', count: 5 },
//       { value: 21, label: 'Филворд Дарья', count: 2 },
//       { value: 22, label: '1000 Секретов', count: 10 },
//       { value: 23, label: 'ЗОЖ', count: 5 },
//       { value: 24, label: 'Бабушкин пирог', count: 5 },
//     ],
//     dateOfLastOrderChange: '2025/11/05',
//     stockType: 'stock',
//     stockNumber: 1,
//     id: '11',
//   },
//   {
//     name: 'Пресс-курьер',
//     fullName: 'Видавничій дім "Пресс-Кур\'єр Україна"',
//     category: 'supplier',
//     categoryPrice: 'cost',
//     taxNumber: '',
//     contractNumber: '№ 81/D',
//     date: '2021-10-01',
//     email: 'ysuhanova_p-c@ukr.net',
//     phone: '+38 044 495 48 43 (44, 45)',
//     adress: '04073, Україна, м. Київ, пр-т С. Бандери, б. 6, корп. 1, оф. 43',
//     active: true,
//     relatedCompanies: [],
//     listOrderedItems: [
//       { value: 2, label: 'Большие буквы', count: 10 },
//       { value: 3, label: 'Веселый дачник', count: 6 },
//       { value: 4, label: 'Гигант сканворд', count: 2 },
//       { value: 5, label: 'Дарья', count: 7 },
//       { value: 6, label: 'Дарья Сканворд', count: 8 },
//       { value: 7, label: 'Дача и дачники', count: 1 },
//       { value: 8, label: 'Дачные советы', count: 4 },
//       { value: 9, label: 'Дачный сканворд', count: 2 },
//       { value: 10, label: 'Ежик', count: 30 },
//       { value: 11, label: 'Загадки истории', count: 6 },
//       { value: 12, label: 'Ключворд', count: 9 },
//       { value: 13, label: 'Крупный шрифт', count: 11 },
//       { value: 14, label: 'Мир судоку', count: 4 },
//       { value: 15, label: 'Страна сканвордов', count: 1 },

//       { value: 17, label: 'Тайны ХХ века', count: 21 },
//       { value: 18, label: 'Тещин компот', count: 9 },
//       { value: 19, label: 'Тещин компот.Судоку', count: 6 },
//       { value: 20, label: 'Титан-кроссворд', count: 5 },
//       { value: 21, label: 'Филворд Дарья', count: 2 },
//       { value: 22, label: '1000 Секретов', count: 10 },

//       { value: 24, label: 'Бабушкин пирог', count: 5 },
//     ],
//     dateOfLastOrderChange: '2025/11/04',
//     stockType: null,
//     stockNumber: null,
//     id: '5',
//   },
//   {
//     name: 'Дибенко20',
//     fullName: 'ФОП Дибенко',
//     category: 'buyer',
//     categoryPrice: 'bulk',
//     taxNumber: null,
//     contractNumber: null,
//     date: null,
//     email: null,
//     phone: null,
//     adress: null,
//     active: true,
//     relatedCompanies: [],
//     listOrderedItems: [
//       { value: 1, label: 'Большие цифры', count: 8 },
//       { value: 2, label: 'Большие буквы', count: 12 },
//       { value: 3, label: 'Веселый дачник', count: 15 },
//       { value: 4, label: 'Гигант сканворд', count: 20 },
//       { value: 5, label: 'Дарья', count: 25 },
//       { value: 6, label: 'Дарья Сканворд', count: 18 },
//       { value: 7, label: 'Дача и дачники', count: 10 },
//       { value: 8, label: 'Дачные советы', count: 14 },
//       { value: 9, label: 'Дачный сканворд', count: 22 },
//       { value: 10, label: 'Ежик', count: 30 },
//       { value: 11, label: 'Загадки истории', count: 16 },
//       { value: 12, label: 'Ключворд', count: 19 },
//       { value: 13, label: 'Крупный шрифт', count: 11 },
//       { value: 14, label: 'Мир судоку', count: 24 },
//       { value: 15, label: 'Страна сканвордов', count: 17 },
//       { value: 16, label: 'Тайны и загадки', count: 13 },
//       { value: 17, label: 'Тайны ХХ века', count: 21 },
//       { value: 18, label: 'Тещин компот', count: 9 },
//       { value: 19, label: 'Тещин компот.Судоку', count: 26 },
//       { value: 20, label: 'Титан-кроссворд', count: 15 },
//       { value: 21, label: 'Филворд Дарья', count: 12 },
//       { value: 22, label: '1000 Секретов', count: 10 },
//       { value: 23, label: 'ЗОЖ', count: 5 },
//       { value: 24, label: 'Бабушкин пирог', count: 15 },
//       { value: 25, label: 'Кулинарный альбом', count: 20 },
//     ],
//     dateOfLastOrderChange: '2025/10/10',
//     stockType: 'shop',
//     stockNumber: 3,
//     id: '20',
//   },
//   {
//     name: 'Дибенко30',
//     fullName: 'ФОП Дибенко',
//     category: 'buyer',
//     categoryPrice: 'bulk',
//     taxNumber: null,
//     contractNumber: null,
//     date: null,
//     email: null,
//     phone: null,
//     adress: null,
//     active: true,
//     relatedCompanies: [],
//     listOrderedItems: [
//       { value: 1, label: 'Большие цифры', count: 8 },
//       { value: 2, label: 'Большие буквы', count: 12 },
//       { value: 3, label: 'Веселый дачник', count: 15 },
//       { value: 4, label: 'Гигант сканворд', count: 20 },
//       { value: 5, label: 'Дарья', count: 25 },
//       { value: 6, label: 'Дарья Сканворд', count: 18 },
//       { value: 7, label: 'Дача и дачники', count: 10 },
//       { value: 8, label: 'Дачные советы', count: 14 },
//       { value: 9, label: 'Дачный сканворд', count: 22 },
//       { value: 10, label: 'Ежик', count: 30 },
//       { value: 11, label: 'Загадки истории', count: 16 },
//       { value: 12, label: 'Ключворд', count: 19 },
//       { value: 13, label: 'Крупный шрифт', count: 11 },
//       { value: 14, label: 'Мир судоку', count: 24 },
//       { value: 15, label: 'Страна сканвордов', count: 17 },
//       { value: 16, label: 'Тайны и загадки', count: 13 },
//       { value: 17, label: 'Тайны ХХ века', count: 21 },
//       { value: 18, label: 'Тещин компот', count: 9 },
//       { value: 19, label: 'Тещин компот.Судоку', count: 26 },
//       { value: 20, label: 'Титан-кроссворд', count: 15 },
//       { value: 21, label: 'Филворд Дарья', count: 12 },
//       { value: 22, label: '1000 Секретов', count: 10 },
//       { value: 23, label: 'ЗОЖ', count: 5 },
//       { value: 24, label: 'Бабушкин пирог', count: 15 },
//       { value: 25, label: 'Кулинарный альбом', count: 20 },
//     ],
//     dateOfLastOrderChange: '2025/10/10',
//     stockType: 'shop',
//     stockNumber: 4,
//     id: '30',
//   },
//   {
//     name: 'Дибенко40',
//     fullName: 'ФОП Дибенко',
//     category: 'buyer',
//     categoryPrice: 'bulk',
//     taxNumber: null,
//     contractNumber: null,
//     date: null,
//     email: null,
//     phone: null,
//     adress: null,
//     active: true,
//     relatedCompanies: [],
//     listOrderedItems: [
//       { value: 1, label: 'Большие цифры', count: 8 },
//       { value: 2, label: 'Большие буквы', count: 12 },
//       { value: 3, label: 'Веселый дачник', count: 15 },
//       { value: 4, label: 'Гигант сканворд', count: 20 },
//       { value: 5, label: 'Дарья', count: 25 },
//       { value: 6, label: 'Дарья Сканворд', count: 18 },
//       { value: 7, label: 'Дача и дачники', count: 10 },
//       { value: 8, label: 'Дачные советы', count: 14 },
//       { value: 9, label: 'Дачный сканворд', count: 22 },
//       { value: 10, label: 'Ежик', count: 30 },
//       { value: 11, label: 'Загадки истории', count: 16 },
//       { value: 12, label: 'Ключворд', count: 19 },
//       { value: 13, label: 'Крупный шрифт', count: 11 },
//       { value: 14, label: 'Мир судоку', count: 24 },
//       { value: 15, label: 'Страна сканвордов', count: 17 },
//       { value: 16, label: 'Тайны и загадки', count: 13 },
//       { value: 17, label: 'Тайны ХХ века', count: 21 },
//       { value: 18, label: 'Тещин компот', count: 9 },
//       { value: 19, label: 'Тещин компот.Судоку', count: 26 },
//       { value: 20, label: 'Титан-кроссворд', count: 15 },
//       { value: 21, label: 'Филворд Дарья', count: 12 },
//       { value: 22, label: '1000 Секретов', count: 10 },
//       { value: 23, label: 'ЗОЖ', count: 5 },
//       { value: 24, label: 'Бабушкин пирог', count: 15 },
//       { value: 25, label: 'Кулинарный альбом', count: 20 },
//     ],
//     dateOfLastOrderChange: '2025/10/10',
//     stockType: 'shop',
//     stockNumber: 5,
//     id: '40',
//   },
//   {
//     name: 'Дибенко50',
//     fullName: 'ФОП Дибенко',
//     category: 'buyer',
//     categoryPrice: 'bulk',
//     taxNumber: null,
//     contractNumber: null,
//     date: null,
//     email: null,
//     phone: null,
//     adress: null,
//     active: true,
//     relatedCompanies: [],
//     listOrderedItems: [
//       { value: 1, label: 'Большие цифры', count: 8 },
//       { value: 2, label: 'Большие буквы', count: 12 },
//       { value: 3, label: 'Веселый дачник', count: 15 },
//       { value: 4, label: 'Гигант сканворд', count: 20 },
//       { value: 5, label: 'Дарья', count: 25 },
//       { value: 6, label: 'Дарья Сканворд', count: 18 },
//       { value: 7, label: 'Дача и дачники', count: 10 },
//       { value: 8, label: 'Дачные советы', count: 14 },
//       { value: 9, label: 'Дачный сканворд', count: 22 },
//       { value: 10, label: 'Ежик', count: 30 },
//       { value: 11, label: 'Загадки истории', count: 16 },
//       { value: 12, label: 'Ключворд', count: 19 },
//       { value: 13, label: 'Крупный шрифт', count: 11 },
//       { value: 14, label: 'Мир судоку', count: 24 },
//       { value: 15, label: 'Страна сканвордов', count: 17 },
//       { value: 16, label: 'Тайны и загадки', count: 13 },
//       { value: 17, label: 'Тайны ХХ века', count: 21 },
//       { value: 18, label: 'Тещин компот', count: 9 },
//       { value: 19, label: 'Тещин компот.Судоку', count: 26 },
//       { value: 20, label: 'Титан-кроссворд', count: 15 },
//       { value: 21, label: 'Филворд Дарья', count: 12 },
//       { value: 22, label: '1000 Секретов', count: 10 },
//       { value: 23, label: 'ЗОЖ', count: 5 },
//       { value: 24, label: 'Бабушкин пирог', count: 15 },
//       { value: 25, label: 'Кулинарный альбом', count: 20 },
//     ],
//     dateOfLastOrderChange: '2025/10/10',
//     stockType: 'shop',
//     stockNumber: 6,
//     id: '50',
//   },
//   {
//     name: 'Дибенко60',
//     fullName: 'ФОП Дибенко',
//     category: 'buyer',
//     categoryPrice: 'bulk',
//     taxNumber: null,
//     contractNumber: null,
//     date: null,
//     email: null,
//     phone: null,
//     adress: null,
//     active: true,
//     relatedCompanies: [],
//     listOrderedItems: [
//       { value: 1, label: 'Большие цифры', count: 8 },
//       { value: 2, label: 'Большие буквы', count: 12 },
//       { value: 3, label: 'Веселый дачник', count: 15 },
//       { value: 4, label: 'Гигант сканворд', count: 20 },
//       { value: 5, label: 'Дарья', count: 25 },
//       { value: 6, label: 'Дарья Сканворд', count: 18 },
//       { value: 7, label: 'Дача и дачники', count: 10 },
//       { value: 8, label: 'Дачные советы', count: 14 },
//       { value: 9, label: 'Дачный сканворд', count: 22 },
//       { value: 10, label: 'Ежик', count: 30 },
//       { value: 11, label: 'Загадки истории', count: 16 },
//       { value: 12, label: 'Ключворд', count: 19 },
//       { value: 13, label: 'Крупный шрифт', count: 11 },
//       { value: 14, label: 'Мир судоку', count: 24 },
//       { value: 15, label: 'Страна сканвордов', count: 17 },
//       { value: 16, label: 'Тайны и загадки', count: 13 },
//       { value: 17, label: 'Тайны ХХ века', count: 21 },
//       { value: 18, label: 'Тещин компот', count: 9 },
//       { value: 19, label: 'Тещин компот.Судоку', count: 26 },
//       { value: 20, label: 'Титан-кроссворд', count: 15 },
//       { value: 21, label: 'Филворд Дарья', count: 12 },
//       { value: 22, label: '1000 Секретов', count: 10 },
//       { value: 23, label: 'ЗОЖ', count: 5 },
//       { value: 24, label: 'Бабушкин пирог', count: 15 },
//       { value: 25, label: 'Кулинарный альбом', count: 20 },
//     ],
//     dateOfLastOrderChange: '2025/10/10',
//     stockType: 'shop',
//     stockNumber: 7,
//     id: '60',
//   },
// ];

const scheduleType = {
  week: { value: 'week', label: 'Неделя' },
  month: { value: 'month', label: 'Месяц' },
  pk: { value: 'pk', label: 'Пресс-курьер' },
  zenit: { value: 'zenit', label: 'Зенит' },
  burda: { value: 'burda', label: 'Бурда' },
  lvov: { value: 'lvov', label: 'Львов' },
  yarmarka: { value: 'yarmarka', label: 'Ярмарка' },
};

const refundsType = [
  { value: 'unlimited', label: 'Безлимитный>' },
  { value: 'limit5', label: '5%' },
  { value: 'limit10', label: '10%' },
  { value: 'limit15', label: '15%' },
  { value: 'limit20', label: '20%' },
  { value: 'limit25', label: '25%' },
  { value: 'non-refund', label: 'Невозвратный' },
];

export const mockOrderProductList = [
  {
    value: 2,
    label: 'Большие буквы',
    scedule: scheduleType.pk,
    weekly: false,
    datesList: ['2025-10-06', '2025-09-06', '2025-11-08', '2025-11-10'],
    isRefund: true,
    isSceduleRefund: true,
    refundsType: null,
  },
  {
    value: 1,
    label: 'Большие цифры',
    scedule: scheduleType.week,
    weekly: false,
    datesList: ['2025-11-01'],
    isRefund: true,
    isSceduleRefund: true,
    refundsType: null,
  },
  {
    value: 3,
    label: 'Веселый дачник',
    scedule: scheduleType.pk,
    weekly: false,
    datesList: ['2025-11-01'],
    isRefund: true,
    isSceduleRefund: true,
    refundsType: null,
  },
  {
    value: 4,
    label: 'Гигант сканворд',
    scedule: scheduleType.pk,
    weekly: false,
    datesList: ['2025-11-01'],
    isRefund: true,
    isSceduleRefund: true,
    refundsType: null,
  },
  {
    value: 5,
    label: 'Дарья',
    scedule: scheduleType.pk,
    weekly: false,
    datesList: ['2025-11-01'],
    isRefund: true,
    isSceduleRefund: true,
    refundsType: null,
  },
  {
    value: 6,
    label: 'Дарья Сканворд',
    scedule: scheduleType.pk,
    weekly: false,
    datesList: ['2025-11-01'],
    isRefund: true,
    isSceduleRefund: true,
    refundsType: null,
  },
  {
    value: 7,
    label: 'Дача и дачники',
    scedule: scheduleType.pk,
    weekly: false,
    datesList: ['2025-11-05'],
    isRefund: true,
    isSceduleRefund: true,
    refundsType: null,
  },
  {
    value: 8,
    label: 'Дачные советы',
    scedule: scheduleType.pk,
    weekly: false,
    datesList: ['2025-11-01'],
    isRefund: true,
    isSceduleRefund: true,
    refundsType: null,
  },
  {
    value: 9,
    label: 'Дачный сканворд',
    scedule: scheduleType.pk,
    weekly: false,
    datesList: ['2025-11-01'],
    isRefund: true,
    isSceduleRefund: true,
    refundsType: null,
  },
  {
    value: 10,
    label: 'Ежик',
    scedule: scheduleType.pk,
    weekly: false,
    datesList: [
      '2025-10-06',
      '2025-09-06',
      '2025-11-08',
      '2025-11-10',
      '2025-10-12',
      '2025-01-14',
      '2025-08-01',
      '2025-07-03',
    ],
    isRefund: true,
    isSceduleRefund: true,
    refundsType: null,
  },
  {
    value: 11,
    label: 'Загадки истории',
    scedule: scheduleType.pk,
    weekly: false,
    datesList: ['2025-11-04'],
    isRefund: true,
    isSceduleRefund: true,
    refundsType: null,
  },
  {
    value: 12,
    label: 'Ключворд',
    scedule: scheduleType.pk,
    weekly: true,
    datesList: ['2025-11-01'],
    isRefund: true,
    isSceduleRefund: true,
    refundsType: null,
  },
  {
    value: 13,
    label: 'Крупный шрифт',
    scedule: scheduleType.zenit,
    weekly: false,
    datesList: ['2025-11-01'],
    isRefund: true,
    isSceduleRefund: true,
    refundsType: null,
  },
  {
    value: 14,
    label: 'Мир судоку',
    scedule: scheduleType.pk,
    weekly: true,
    datesList: ['2025-11-01'],
    isRefund: true,
    isSceduleRefund: true,
    refundsType: null,
  },
  {
    value: 15,
    label: 'Страна сканвордов',
    scedule: scheduleType.pk,
    weekly: false,
    datesList: ['2025-11-03'],
    isRefund: true,
    isSceduleRefund: true,
    refundsType: null,
  },
  {
    value: 16,
    label: 'Тайны и загадки',
    scedule: scheduleType.pk,
    weekly: false,
    datesList: ['2025-11-01'],
    isRefund: true,
    isSceduleRefund: true,
    refundsType: null,
  },
  {
    value: 17,
    label: 'Тайны ХХ века',
    scedule: scheduleType.pk,
    weekly: false,
    datesList: ['2025-11-01'],
    isRefund: true,
    isSceduleRefund: true,
    refundsType: null,
  },
  {
    value: 18,
    label: 'Тещин компот',
    scedule: scheduleType.pk,
    weekly: false,
    datesList: ['2025-11-01'],
    isRefund: true,
    isSceduleRefund: true,
    refundsType: null,
  },
  {
    value: 19,
    label: 'Тещин компот.Судоку',
    scedule: scheduleType.pk,
    weekly: false,
    datesList: ['2025-11-01'],
    isRefund: true,
    isSceduleRefund: true,
    refundsType: null,
  },
  {
    value: 20,
    label: 'Титан-кроссворд',
    scedule: scheduleType.pk,
    weekly: false,
    datesList: ['2025-11-01'],
    isRefund: true,
    isSceduleRefund: true,
    refundsType: null,
  },
  {
    value: 21,
    label: 'Филворд Дарья',
    scedule: scheduleType.pk,
    weekly: true,
    datesList: ['2025-11-01'],
    isRefund: true,
    isSceduleRefund: true,
    refundsType: null,
  },
  {
    value: 22,
    label: '1000 Секретов',
    scedule: scheduleType.pk,
    weekly: false,
    datesList: ['2025-11-01'],
    isRefund: true,
    isSceduleRefund: true,
    refundsType: null,
  },
  {
    value: 23,
    label: 'ЗОЖ',
    scedule: scheduleType.month,
    weekly: false,
    datesList: ['2025-11-01'],
    isRefund: false,
    isSceduleRefund: false,
    refundsType: null,
  },
  {
    value: 24,
    label: 'Бабушкин пирог',
    scedule: scheduleType.pk,
    weekly: false,
    datesList: ['2025-11-02'],
    isRefund: true,
    isSceduleRefund: true,
    refundsType: null,
  },
  {
    value: 25,
    label: 'Кулинарный альбом',
    scedule: scheduleType.month,
    weekly: false,
    datesList: ['2025-10-02', '2025-11-02'],
    isRefund: true,
    isSceduleRefund: false,
    refundsType: null,
  },
];
