export const FORM_TYPES = {
  CONTRACTOR: 'CONTRACTOR',
  CONTRACTOR_ADDITIONAL: 'CONTRACTOR_ADDITIONAL',
  CONTRACTOR_ORDER: 'CONTRACTOR_ORDER',
  GOODS: 'GOODS',
  PAYMENT: 'PAYMENT',
  INVOICE: 'INVOICE',
  INVOICE_PRODUCTS_ADDITIONAL: 'INVOICE_PRODUCTS_ADDITIONAL',
  INVOICE_EMPTY_ADDITIONAL: 'INVOICE_EMPTY_ADDITIONAL',
  PRINT_INVOICE: 'invoice',
  PRINT_PRICELIST: 'priceList',
  PRINT_RECEIVABLE: 'receivable',
};

export const FORM_ACTIONS = {
  CREATE: 'create',
  EDIT: 'edit',
  COPY: 'copy',
};
