export const emptyGoodsObject = {
  active: true,
  name: '',
  fullName: '',
  supplier: '',
  cost: 0,
  superBulk: 0,
  bulk: 0,
  retail: 0,
  dateStart: null,
  dateEnd: null,
};

export const testArr = [
  {
    key: '1',
    active: true,
    name: 'fff',
    fullName: '',
    supplier: '',
    cost: 0,
    superBulk: 0,
    bulk: 0,
    retail: 0,
    dateStart: null,
    dateEnd: null,
  },
  {
    key: '2',
    active: true,
    name: 'ddd',
    fullName: '',
    supplier: '',
    cost: 0,
    superBulk: 0,
    bulk: 0,
    retail: 0,
    dateStart: null,
    dateEnd: null,
  },
];
